### ISSUE TITLE
issue: be explicit about naming of `Adaptor` classes in backend implementations

### ISSUE THREAD

**Issue by alisterburt** [tlambert03/microvis#23]
taken from @tlambert03 in #14 

We currently use the phrase 'backend implementations' to describe... implementations of visualisation backends according to a given microvis `Backend` specification -> it would be easier to reason about these if we explicitly call them `Adaptor`s

new logic
`Adaptor` classes implement the `Backend` for a particular microvis `VisModel`

**Comment by tlambert03** [comment]
> Adaptor classes implement the Backend for a particular microvis VisModel

very slight modification:   implement the "protocol" or "interface"

so... summarizing:

- **model**: (VisModel)... our core models
- **backend**: the actual library (vispy, pygfx)
- **adaptor**: the object that sits in between the backend and the VisModel (a true [Adapter](https://refactoring.guru/design-patterns/adapter)) ... side question: "adaptor" or "adapter"?? :joy:
- **protocol**: an ABC or interface that the adaptor needs to implement.  (currently called `BackendAdaptor` ... do we like that?  or should it be `AdaptorProtocol`?)

**Comment by alisterburt** [comment]
hahah oh god, I came to the same conclusion in #14 😆 

I like protocol, `VisProtocol` nicely mirrors `VisModel`, `AdaptorProtocol` feels slightly wrong

so...
model: (VisModel)... our core models
protocol: (VisProtocol) an ABC or interface that an adaptor for a given backend needs to implement.
backend: the actual library doing the things the protocol says it should (vispy, pygfx)
adaptor: the object that sits in between the backend and the VisModel

> ... side question: "adaptor" or "adapter"?? 😂
hahhah - adapter makes me cringe in the same way as visualize instead of visualise, total UK-ism and completely happy with either, I leave it up to you

**Comment by alisterburt** [comment]
crossed wires with #14 - let's just call them what they are, `Protocol` as @tlambert03 suggested 🙂

**Comment by tlambert03** [comment]
> total UK-ism and completely happy with either, I leave it up to you

yeah, I know it's a UK/US thing... but I actually googled around on this a bit.  There's of course no right answer. but even in the US, I think "adapter" has a slight implication of a person ("one" who adapts) and "adaptor" has a vague feeling of a device ("thing" that adapts).  So, that's why I went with adaptor  it was only https://refactoring.guru/design-patterns/adapter that made me rethink it just now :)  
but screw it.  adaptor it is

**Comment by alisterburt** [comment]
<3

**Comment by alisterburt** [comment]
hm, I'm not sure now, you're right that that's literally the only thing the protocol defines... let's go with that! `CameraAdaptorProtocol`

**Comment by alisterburt** [comment]
closed by #25
