### ISSUE TITLE
Camera API thoughts

### ISSUE THREAD

**Issue by alisterburt** [tlambert03/microvis#37]
# Camera API thoughts

Quickly jotted down some ideas about our camera model

## Basic questions at the outset

- do we want one camera model which works in 2D and 3D? we could explicitly separate these
- do we want to nD-ify the camera? (e.g. napari has an nD view direction attribute and a notion of nD position

My gut feeling is that we should unify 2D and 3D and that the camera model should be 3D, never nD. This makes it relatively easy to implement non-orthogonal slicing in 3D.

## What is a 3D camera
The most useful mental model for a camera I found was the pygfx one

> The purpose of a camera is to define the viewpoint for rendering a scene.
    This viewpoint consists of its position (in the world) and its projection.

Simple! I particularly like the emphasis on the position being the position of the viewpoint, not the position of the camera itself. For any camera then the data model is a single 4x4 matrix which encapsulates the orientation, position and potentially also perspective transforms - we can provide views and setters into this to expose attributes like position, view+up direction, euler angles... whatever we want

c.f.
[vispy base camera](https://vispy.org/api/vispy.scene.cameras.base_camera.html), [pygfx base camera](https://github.com/pygfx/pygfx/blob/6688bfd5b6dcbca81d8d25163593e4aee4ad224c/pygfx/cameras/_base.py#L5-L21), [three.js base camera](https://threejs.org/docs/#api/en/cameras/Camera),
[nicolas rougier's notes on projective geometry](https://www.labri.fr/perso/nrougier/python-opengl/#basic-mathematics)

## Proposed camera model

I think this simple model with the few conveniences provided gives us everything we need to really get going - perspective is a bit buggy in a few vispy visuals so I don't think we should go there yet :)

```python
class Camera:
    projection_matrix: Matrix4x4

    @property
    def position() -> Tuple[float, float, float]
         """the viewpoint in 3D - what the camera is looking at."""

    @property
    def zoom() -> float:
        """zoom of 1 means 1 px on screen has the same area as 1 unscaled 2D image pixel."""

    @property
    def view_direction() -> Tuple[float, float, float]:

    @property
    def up_direction() -> Tuple[float, float, float]:

    def reset_rotation() -> None:
        """reset rotation to default."""

    def rotate_x/y/z(theta: float)
        """Rotate the camera around the x/y/z axes by 'theta' degrees."""
  
```

**Comment by alisterburt** [comment]
also, I don't think the potential 'reset_range' API should live on the camera, it is a function of both the camera and the canvas... it could live on the camera and take the canvas as an arg or live on some higher level object with access to both

**Comment by tlambert03** [comment]
> My gut feeling is that we should unify 2D and 3D and that the camera model should be 3D, never nD.

mine too! :)

> I don't think the potential 'reset_range' API should live on the camera

I agree!  maybe it should live on the `View`  (which is really the thing that defines how large the camera viewbox can be).  Canvas, is just a minor abstraction on top of that, with the ability to hold multiple views, but if you had 4 views on a canvas (say, for a 2x2 orthviewer), you'd want reset_range to only fill the quadrant for each view.

**Comment by tlambert03** [comment]
model looks good to me!  If we can compute all of those properties from a matrix, and set the matrix accordingly with some conveniences, that seems like a very good single-source of truth

**Comment by alisterburt** [comment]
> View (which is really the thing that defines how large the camera viewbox can be). Canvas, is just a minor abstraction on top of that, with the ability to hold multiple views

this was more useful to me than it should have been 😆 thanks for clarifying! 

> model looks good to me! If we can compute all of those properties from a matrix, and set the matrix accordingly with some conveniences, that seems like a very good single-source of truth

Cool - I'll get to work :)

**Comment by alisterburt** [comment]
closed as consensus reached
